baseURL = "http://example.org/"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "cv/resume"
    author = "Neline Eyabe"
    description = "My portfolio"
    copyright = "copyright 2024"
    theme = "dark" # `dark` or `light`

    # Profile section
    [params.profile]
        name = "Neline Eyabe"
        title = "Data Science."
        photo = "/images/pic1.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "#"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/Nelinekid"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "ai ai-google-scholar"
        url = "#"
        title = "Google Scholar"
		
		[[params.social.list]]
        icon = "ai ai-researchgate"
        url = "#"
        title = "ResearchGate"		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Advance level"
        college = "Government Balingual High School Yaounde"
        dates = "2020 - 2021"
        thesis_title = "Title of the dissertation"
        thesis_link = "#"

        [[params.education.list]]
        degree = "ordinary level"
        college = "CEGET Bonaberi Douala"
        dates = "2017- 2018"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "French"
        level = "Basic"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Sports"
		
		[[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Cooking"


        [[params.hobbies.list]]
        interest = "gaming"

    [params.aboutme]
        description = "My name is Neline Eyabe,i am a level 300 student at the University  Of Buea with a strong interest Data Science. I am driven by a desire to give innovative solutions,and a passion for problem solvng. I am excited to apply my skills and knowledge to real world projects and contribute to giving meaning and useful data to organizations."

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Intern at N.TECH"
        dates = "1 month"
		link = "#"
        company = "Network Technologies Yaounde"


        [[params.jobs.list]]
        position = "Intern at IKNITE"
        dates = "2 months"
		link = "#"
        company = "IKNITE SPACE"
        
    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Restuarant Site"
        url = "#"
        description = "Description of the *awesome* project 1"
		
		[[params.projects.list]]
        title = "Quizz App"
        url = "#"
        
    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "html"
        skillrating = 50 # out of 100
                
        [[params.skills.list]]
        skill = "Python programming"
        skillrating = 45 #
		
        [[params.skills.list]]
        skill = "Java"
        skillrating = 30#

        [[params.skill.list]]
        skill = "Dart"
        skillrating = 30.5 #

