baseURL = "http://example.org/"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "cv/resume"
    author = "Charles Tima"
    description = "My portfolio"
    copyright = "copyright 2024"
    theme = "dark" # `dark` or `light`

    # Profile section
    [params.profile]
        name = "Charles Tima"
        title = "Data Science."
        photo = "/images/IMG_4139.JPG"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "#"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"  
        url = "https://github.com/Gambi18"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "ai ai-google-scholar"
        url = "#"
        title = "Google Scholar"
		
		[[params.social.list]]
        icon = "ai ai-researchgate"
        url = "#"
        title = "ResearchGate"		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Advance level"
        college = "Sacred Heart College Mankon"
        dates = "2020 - 2022"
        thesis_title = "Title of the dissertation"
        thesis_link = "#"

        [[params.education.list]]
        degree = "ordinary level"
        college = "Sacred Heart College Mankon"
        dates = "2015- 2020"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Sports"
		
		[[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Gaming"

    [params.aboutme]
        description = "My name is Charles Tima,i am a level 300 student at the University  Of Buea with a strong interest Data Science. I am driven by a desire to give innovative solutions,and a passion for problem solvng. I am excited to apply my skills and knowledge to real world projects and contribute to giving meaning and useful data to organizations."

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Intern"
        dates = "2 months"
		link = "#"
        company = "Active Spaces"


        [[params.jobs.list]]
        position = "Intern at IKNITE"
        dates = "2 months"
		link = "#"
        company = "IKNITE SPACE"
        
    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Restuarant Site"
        url = "#"
        description = "Description of the *awesome* project 1"
		
		[[params.projects.list]]
        title = "Quizz App"
        url = "#"
        
    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "html"
        skillrating = 70 # out of 100
                
        [[params.skills.list]]
        skill = "Python programming"
        skillrating = 30 #
		
        [[params.skills.list]]
        skill = "Java"
        skillrating = 25#

        [[params.skill.list]]
        skill = "Dart"
        skillrating = 10 #

